export const userSignup = async (req, res) => {
	try {
		console.log(req.body)
	} catch (err) {
		console.log(err)
	}
}
